(define l_source 0.030)
(define l_drain 0.030)
(define l_spacer 0.006)
(define l_gate 0.018)
(define wall_1 0.005)
(define wall_2 0.005)
(define w_metal 0.00578)
(define h_metal 0.005)
(define oxide_HfO2 0.0011)
(define oxide_SiO2 0.0006)
(define height_channel 0.005)
(define m_height_channel 0.008)
(define width_channel 0.023)
(define SiN_top_height 0.0213)
(define substrate 0.010)
(define h_BDI 0.015)

(define x0 0.0)
(define x1(+ x0 w_metal))
(define x2(+ x1 oxide_HfO2))
(define x3(+ x2 oxide_SiO2))
(define x4(+ x3 width_channel))
(define x5(+ x4 oxide_HfO2))
(define x6(+ x5 oxide_SiO2))
(define x7(+ x6 wall_1))
(define x8(+ x7 wall_2))
(define x9(+ x8 oxide_SiO2))
(define x10(+ x9 oxide_HfO2))
(define x11(+ x10 width_channel))
(define x12(+ x11 oxide_SiO2))
(define x13(+ x12 oxide_HfO2))
(define x14(+ x13 w_metal))

(define y0 0.0)
(define y1(+ y0 l_source))
(define y2(+ y1 l_spacer))
(define y3(+ y2 l_gate))
(define y4(+ y3 l_spacer))
(define y5(+ y4 l_drain))

(define z0 0.0)
(define z1(+ z0 substrate))
(define z5(+ z1 h_BDI))
(define z6(+ z5 h_metal))
(define z7(+ z6 oxide_HfO2))
(define z8(+ z7 oxide_SiO2))
(define z9(+ z8 height_channel))
(define z10(+ z9 oxide_SiO2))
(define z11(+ z10 oxide_HfO2))
(define z12(+ z11 h_metal))
(define z13(+ z12 oxide_HfO2))
(define z14(+ z13 oxide_SiO2))
(define z15(+ z14 height_channel))
(define z16(+ z15 oxide_SiO2))
(define z17(+ z16 oxide_HfO2))
(define z18(+ z17 SiN_top_height))
(define z19(+ z18 oxide_SiO2))
(define z20(+ z19 oxide_HfO2))
(define z21(+ z20 m_height_channel))

(sdegeo:create-cuboid (position x0 y0 z0) (position x14 y5 z1) "Silicon" "substrate_Si")
(sdegeo:create-cuboid (position x6 y0 z1) (position x8 y5 z18) "SiO2" "wall_SiN")
(sdegeo:create-cuboid (position x0 y0 z1) (position x6 y5 z5) "Silicon" "BDI_N")
(sdegeo:create-cuboid (position x8 y0 z1) (position x14 y5 z5) "Silicon" "BDI_P")
(sdegeo:create-cuboid (position x0 y1 z5) (position x14 y4 z21) "SiO2" "surrounding_si3n4")
(sdegeo:create-cuboid (position x0 y2 z5) (position x7 y3 z21) "Aluminum" "metal_n")
(sdegeo:create-cuboid (position x7 y2 z5) (position x14 y3 z21) "TiN" "metal_p")
(sdegeo:create-cuboid (position x4 y2 z5) (position x10 y3 z20) "HfO2" "along_wall_HfO2")
(sdegeo:create-cuboid (position x5 y2 z5) (position x9 y3 z19) "SiO2" "along_wall_SiO2")
(sdegeo:create-cuboid (position x1 y2 z6) (position x5 y3 z11) "HfO2" "gateox_ch1_n")
(sdegeo:create-cuboid (position x9 y2 z6) (position x13 y3 z11) "HfO2" "gateox_ch1_p")
(sdegeo:create-cuboid (position x1 y2 z12) (position x5 y3 z17) "HfO2" "gateox_ch2_n")
(sdegeo:create-cuboid (position x9 y2 z12) (position x13 y3 z17) "HfO2" "gateox_ch2_p")
(sdegeo:create-cuboid (position x2 y2 z7) (position x6 y3 z10) "SiO2" "gateox_2ch1_n")
(sdegeo:create-cuboid (position x8 y2 z7) (position x12 y3 z10) "SiO2" "gateox_2ch1_p")
(sdegeo:create-cuboid (position x2 y2 z13) (position x6 y3 z16) "SiO2" "gateox_2ch2_n")
(sdegeo:create-cuboid (position x8 y2 z13) (position x12 y3 z16) "SiO2" "gateox_2ch2_p")
(sdegeo:create-cuboid (position x3 y1 z8) (position x6 y4 z9) "Silicon" "Nano_sheet_1_n") 
(sdegeo:create-cuboid (position x3 y1 z14) (position x6 y4 z15) "Silicon" "Nano_sheet_2_n") 
(sdegeo:create-cuboid (position x8 y1 z8) (position x11 y4 z9) "Silicon" "Nano_sheet_1_p") 
(sdegeo:create-cuboid (position x8 y1 z14) (position x11 y4 z15) "Silicon" "Nano_sheet_2_p") 
(sdegeo:create-cuboid (position x0 y0 z5) (position x6 y1 z18) "Silicon" "Source_region_n")
(sdegeo:create-cuboid (position x8 y0 z5) (position x14 y1 z18) "Silicon" "Source_region_p")
(sdegeo:create-cuboid (position x0 y4 z5) (position x6 y5 z18) "Silicon" "Drain_region_n")
(sdegeo:create-cuboid (position x8 y4 z5) (position x14 y5 z18) "Silicon" "Drain_region_p")

(sdegeo:define-contact-set "SN" 4 (color:rgb 1 0 0 ) "##")
(sdegeo:define-contact-set "DN" 4 (color:rgb 1 1 0 ) "##")
(sdegeo:define-contact-set "G" 4 (color:rgb 1 0 1 ) "##")
(sdegeo:define-contact-set "SP" 4 (color:rgb 1 1 1 ) "##")
(sdegeo:define-contact-set "DP" 4 (color:rgb 0 0 0 ) "##")

(sdegeo:set-current-contact-set "SP")
(sdegeo:set-contact (list (car (find-face-id (position 0.05827 0.015 z18)))) "SP")
(sdegeo:set-current-contact-set "DP")
(sdegeo:set-contact (list (car (find-face-id (position 0.05827 0.075 z18)))) "DP")
(sdegeo:set-current-contact-set "DN")
(sdegeo:set-contact (list (car (find-face-id (position 0.01609 0.075 z18)))) "DN")
(sdegeo:set-current-contact-set "SN")
(sdegeo:set-contact (list (car (find-face-id (position 0.01609 0.015 z18)))) "SN")
(sdegeo:set-current-contact-set "G")
(sdegeo:set-contact (list (car (find-face-id (position 0.01859 0.045 z21))) (car (find-face-id (position 0.05577 0.045 z21)))) "G")

(sdedr:define-constant-profile "ConstantProfileDefinition_1" "ArsenicActiveConcentration" 1e+20)
(sdedr:define-constant-profile-region "ConstantProfilePlacement_1" "ConstantProfileDefinition_1" "Source_region_n")
(sdedr:define-constant-profile "ConstantProfileDefinition_2" "ArsenicActiveConcentration" 1e+20)
(sdedr:define-constant-profile-region "ConstantProfilePlacement_2" "ConstantProfileDefinition_2" "Drain_region_n")
(sdedr:define-constant-profile "ConstantProfileDefinition_4" "BoronActiveConcentration" 4e+16)
(sdedr:define-constant-profile-region "ConstantProfilePlacement_4" "ConstantProfileDefinition_4" "Nano_sheet_1_n")
(sdedr:define-constant-profile "ConstantProfileDefinition_5" "BoronActiveConcentration" 4e+16)
(sdedr:define-constant-profile-region "ConstantProfilePlacement_5" "ConstantProfileDefinition_5" "Nano_sheet_2_n")
(sdedr:define-constant-profile "ConstantProfileDefinition_7" "BoronActiveConcentration" 1e+20)
(sdedr:define-constant-profile-region "ConstantProfilePlacement_7" "ConstantProfileDefinition_7" "Source_region_p")
(sdedr:define-constant-profile "ConstantProfileDefinition_8" "BoronActiveConcentration" 1e+20)
(sdedr:define-constant-profile-region "ConstantProfilePlacement_8" "ConstantProfileDefinition_8" "Drain_region_p")
(sdedr:define-constant-profile "ConstantProfileDefinition_9" "ArsenicActiveConcentration" 9e+15)
(sdedr:define-constant-profile-region "ConstantProfilePlacement_9" "ConstantProfileDefinition_9" "Nano_sheet_1_p")
(sdedr:define-constant-profile "ConstantProfileDefinition_10" "ArsenicActiveConcentration" 9e+15)
(sdedr:define-constant-profile-region "ConstantProfilePlacement_10" "ConstantProfileDefinition_10" "Nano_sheet_2_p")

(sdedr:define-refeval-window "RefWin.Global" "Cuboid" (position x0 y0 z0) (position x14 y5 z21))
(sdedr:define-refinement-size "RefDef.Global" 0.1 0.1 0.1 0.005 0.005 0.005 )
(sdedr:define-refinement-placement "Place.Global" "RefDef.Global" "RefWin.Global" )

(sdedr:define-refeval-window "RefWin.SOURCE_n" "Cuboid" (position x0 y0 z5) (position x6 y1 z18) )
(sdedr:define-refinement-size "RefDef.SOURCE_n" 0.02 0.02 0.02 0.005 0.005 0.005 )
(sdedr:define-refinement-placement "PlaceRF.SOURCE_n" "RefDef.SOURCE_n" "RefWin.SOURCE_n")
(sdedr:define-refeval-window "RefWin.DRAIN_n" "Cuboid" (position x0 y4 z5) (position x6 y5 z18) )
(sdedr:define-refinement-size "RefDef.DRAIN_n" 0.02 0.02 0.02 0.005 0.005 0.005 )
(sdedr:define-refinement-placement "PlaceRF.DRAIN_n" "RefDef.DRAIN_n" "RefWin.DRAIN_n")
(sdedr:define-refeval-window "RefWin.SOURCE_p" "Cuboid" (position x8 y0 z5) (position x14 y1 z18) )
(sdedr:define-refinement-size "RefDef.SOURCE_p" 0.02 0.02 0.02 0.005 0.005 0.005 )
(sdedr:define-refinement-placement "PlaceRF.SOURCE_p" "RefDef.SOURCE_p" "RefWin.SOURCE_p")
(sdedr:define-refeval-window "RefWin.DRAIN_p" "Cuboid" (position x8 y4 z5) (position x14 y5 z18) )
(sdedr:define-refinement-size "RefDef.DRAIN_p" 0.02 0.02 0.02 0.005 0.005 0.005 )
(sdedr:define-refinement-placement "PlaceRF.DRAIN_p" "RefDef.DRAIN_p" "RefWin.DRAIN_p")

(sdedr:define-refinement-size "RefDef.Channel" 0.004 0.02 0.004 0.001 0.005 0.001 )
(sdedr:define-refinement-function "RefDef.Channel" "MaxLenInt" "Silicon" "SiO2" 0.0005 1.3 "DoubleSide")

(sdedr:define-refeval-window "RefWin.ch1_n" "Cuboid" (position x3 y1 z8) (position x6 y4 z9) )
(sdedr:define-refinement-placement "PlaceRF.ch1_n" "RefDef.Channel" "RefWin.ch1_n")

(sdedr:define-refeval-window "RefWin.ch2_n" "Cuboid" (position x3 y1 z14) (position x6 y4 z15) )
(sdedr:define-refinement-placement "PlaceRF.ch2_n" "RefDef.Channel" "RefWin.ch2_n")

(sdedr:define-refeval-window "RefWin.ch1_p" "Cuboid" (position x8 y1 z8) (position x11 y4 z9) )
(sdedr:define-refinement-placement "PlaceRF.ch1_p" "RefDef.Channel" "RefWin.ch1_p")

(sdedr:define-refeval-window "RefWin.ch2_p" "Cuboid" (position x8 y1 z14) (position x11 y4 z15) )
(sdedr:define-refinement-placement "PlaceRF.ch2_p" "RefDef.Channel" "RefWin.ch2_p")

(sde:build-mesh "n@node@")
